### ISSUE TITLE
No visits to log to record review error

### ISSUE THREAD

**Issue by RichardLitt** [dkhamsing/frankenstein#17]
I am trying to get frankenstein to automatically open a PR, and I am getting this error: 

```sh
10:47 ~/src/libp2p 🐕  frankenstein libp2p/go-libp2p
🏃  there are previous runs for libp2p/go-libp2p in logs
1 file
logs/1475074076-2016-09-28-libp2p-go-libp2p.frankenstein
2016-09-26 23:23:09 UTC
Found: master for libp2p/go-libp2p — libp2p implementation in Go — 512⭐️  — last updated 2 days ago
🏃  Processing links for libp2p/go-libp2p ...
🔎  Checking 14 links
⚪  https://travis-ci.org/ipfs/go-libp2p.svg?branch=master
✅  https://raw.githubusercontent.com/diasdavid/specs/libp2p-spec/protocol/network/figs/logo.png
✅  https://godoc.org/github.com/ipfs/go-libp2p?status.svg
✅  https://img.shields.io/badge/freenode-%23ipfs-blue.svg?style=flat-square
🔶  301 https://github.com/ipfs/go-libp2p
🔶  301 https://github.com/diasdavid/js-libp2p
✅  https://github.com/ipfs/ipfs
✅  https://github.com/libp2p/specs
✅  https://github.com/libp2p/specs
✅  https://github.com/libp2p/specs
✅  https://github.com/whyrusleeping/libp2p-examples/
✅  https://img.shields.io/badge/made%20by-Protocol%20Labs-blue.svg?style=flat-square
🔶  301 https://github.com/diasdavid/libp2p-website
✅  https://github.com/libp2p/specs

📋  frankenstein results: 3 issues (23%)
   3 of 13 links
🔶  301 https://github.com/ipfs/go-libp2p
🔶  301 https://github.com/diasdavid/js-libp2p
🔶  301 https://github.com/diasdavid/libp2p-website

🔶  3 redirects
https://github.com/ipfs/go-libp2p redirects to 
https://github.com/libp2p/go-libp2p 
  ipfs/go- was removed
  !!!
  /go-libp2p was added
  !!!

https://github.com/diasdavid/js-libp2p redirects to 
https://github.com/libp2p/js-libp2p 
  diasdavid/js- was removed
  !!!
  /js-libp2p was added
  !!!

https://github.com/diasdavid/libp2p-website redirects to 
https://github.com/libp2p/website 
  diasdavid/ was removed
  !!!
  - was replaced by /
  !!!

Wrote redirects replaced to logs/1475074143-2016-09-28-libp2p-go-libp2p-updated
Wrote log to logs/1475074143-2016-09-28-libp2p-go-libp2p.frankenstein

🕐  Time elapsed: 3.04 seconds

🏃  No failures for libp2p/go-libp2p
io_record_review no visits log to record review for libp2p/go-libp2p
/Users/richard/.rvm/gems/ruby-2.1.5/gems/frankenstein-0.1.0/lib/frankenstein/io.rb:172:in `read': No such file or directory @ rb_sysopen - logs/franken_visits.json (Errno::ENOENT)
	from /Users/richard/.rvm/gems/ruby-2.1.5/gems/frankenstein-0.1.0/lib/frankenstein/io.rb:172:in `io_json_read'
	from /Users/richard/.rvm/gems/ruby-2.1.5/gems/frankenstein-0.1.0/lib/frankenstein/io.rb:45:in `io_record_pull_exists'
	from /Users/richard/.rvm/gems/ruby-2.1.5/gems/frankenstein-0.1.0/lib/frankenstein/io.rb:36:in `io_record_pull_check'
	from /Users/richard/.rvm/gems/ruby-2.1.5/gems/frankenstein-0.1.0/lib/frankenstein.rb:196:in `<module:Frankenstein>'
	from /Users/richard/.rvm/gems/ruby-2.1.5/gems/frankenstein-0.1.0/lib/frankenstein.rb:16:in `<top (required)>'
	from /Users/richard/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /Users/richard/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /Users/richard/.rvm/gems/ruby-2.1.5/gems/frankenstein-0.1.0/bin/frankenstein:4:in `<top (required)>'
	from /Users/richard/.rvm/gems/ruby-2.1.5/bin/frankenstein:23:in `load'
	from /Users/richard/.rvm/gems/ruby-2.1.5/bin/frankenstein:23:in `<main>'
	from /Users/richard/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/richard/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

```

Thoughts?

**Comment by dkhamsing** [comment]
@RichardLitt hi, not on a computer right now 😅  

can you try this in your frankenstein/ directory

```shell
cd bin/
./frankenstein libp2p/go-libp2p
```

**Comment by RichardLitt** [comment]
Same problem. 

No rush if you're AFK for a while! Saw you haven't committed in a bit, hope you're having fun somewhere.

**Comment by dkhamsing** [comment]
okie. sorry again! be back later

**Comment by dkhamsing** [comment]
@RichardLitt i think this fixes it, can you pull for latest changes and try again

**Comment by RichardLitt** [comment]
Yes! This works, fixes this issue. Thank you.
