### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by m1guelpf** [dkhamsing/frankenstein#21]
```
🏃  Processing links for https://miguelpiedrafita.com/@ ...
/home/m1guelpiedrafita/git/frankenstein/lib/frankenstein.rb:152:in `<module:Frankenstein>': undefined method `net_status' for Frankenstein:Module (NoMethodError)
	from /home/m1guelpiedrafita/git/frankenstein/lib/frankenstein.rb:16:in `<top (required)>'
	from /home/m1guelpiedrafita/git/frankenstein/bin/frankenstein:4:in `require'
	from /home/m1guelpiedrafita/git/frankenstein/bin/frankenstein:4:in `<top (required)>'
	from /home/m1guelpiedrafita/.rvm/gems/ruby-2.4.0/bin/frankenstein:23:in `load'
	from /home/m1guelpiedrafita/.rvm/gems/ruby-2.4.0/bin/frankenstein:23:in `<main>'
	from /home/m1guelpiedrafita/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/m1guelpiedrafita/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dkhamsing** [comment]
hm i think that's part of `awesome_bot`

can you try 

```
(sudo) gem install awesome_bot
```


and report back

**Comment by dkhamsing** [comment]
btw this project is hella buggy :)

**Comment by dkhamsing** [comment]
closing for lack of activity
